from __future__ import annotations

import os


CASE_NAME_PREFIXES = ("\u6570\u636e\u811a\u672c-", "test-")

DATA_SCRIPT_PROJECT_NAME = "日本站测试"

LOGIN_CASE_NAME = "\u767b\u5f55"

CART_CASE_NAME = "\u52a0\u5165\u8d2d\u7269\u8f66"

FRONTEND_UNIVERSAL_ACCOUNT_PASSWORD = os.getenv("FRONTEND_ACCOUNT_PASSWORD", "xiaolin666@@")

DATA_SCRIPT_API_CASES = [
    {
        "key": "client_login",
        "case_name": "\u6570\u636e\u811a\u672c-\u524d\u53f0\u767b\u5f55",
        "url": "/client/userLogin",
        "body": {"account": "{{account}}", "password": "{{password}}", "client_tool": "{{client_tool}}"},
        "extract": {"userToken": "json.data.userToken"},
    },
    {
        "key": "client_search_goods",
        "case_name": "\u6570\u636e\u811a\u672c-\u641c\u7d22\u5546\u54c1",
        "url": "/client/searchGoods",
        "body": {"keywords": "{{keyword}}", "shop_type": "{{shop_type}}", "page": "{{page}}", "pageSize": "{{page_size}}"},
    },
    {
        "key": "client_store_shop_id",
        "case_name": "\u6570\u636e\u811a\u672c-\u83b7\u53d6\u5e97\u94fa\u4fe1\u606f",
        "url": "/client/getStoreShopId",
        "body": {"keywords": "{{shop_keywords}}"},
    },
    {
        "key": "client_cart_add",
        "case_name": "\u6570\u636e\u811a\u672c-\u52a0\u5165\u8d2d\u7269\u8f66",
        "url": "/client/cart.goodsToCart",
        "body": {"to_cart[0][goods_id]": "{{goods_id}}", "to_cart[0][num]": "{{num}}"},
    },
    {
        "key": "client_cart_list",
        "case_name": "\u6570\u636e\u811a\u672c-\u8d2d\u7269\u8f66\u5217\u8868",
        "url": "/client/cart.goodsCartList",
        "body": {"priceCut": "{{price_cut}}"},
    },
    {
        "key": "client_cart_edit",
        "case_name": "\u6570\u636e\u811a\u672c-\u7f16\u8f91\u8d2d\u7269\u8f66\u5546\u54c1",
        "url": "/client/cart.goodsCartEdit",
        "body": {"id": "{{cart_id}}", "num": "{{num}}", "price": "{{price}}", "detail": "{{detail}}", "sku_id": "{{sku_id}}", "spec_id": "{{spec_id}}", "pic": "{{pic}}", "client_remark": "{{client_remark}}"},
    },
    {
        "key": "client_order_create",
        "case_name": "\u6570\u636e\u811a\u672c-\u521b\u5efa\u65b0\u8ba2\u5355",
        "url": "/client/order.orderCreate",
        "body": {"create_type": "{{create_type}}", "order_sn": "{{order_sn}}", "client_remark": "{{client_remark}}", "logistics_id": "{{logistics_id}}"},
        "extract": {"order_sn": "json.data.order_sn"},
    },
    {
        "key": "client_order_list",
        "case_name": "\u6570\u636e\u811a\u672c-\u524d\u53f0\u8ba2\u5355\u5217\u8868",
        "url": "/client/order.orderList",
        "body": {"status_name": "{{order_status_name}}", "page": "{{page}}", "pageSize": "{{page_size}}"},
    },
    {
        "key": "client_warehouse_list",
        "case_name": "\u6570\u636e\u811a\u672c-\u4ed3\u5e93\u5546\u54c1\u5217\u8868",
        "url": "/client/wms.stockAutoList",
        "body": {"children_id": "{{children_id}}", "for_sn_set": "{{for_sn_set}}", "tag_set": "{{tag_set}}", "client_remark": "{{client_remark}}", "sort_type": "{{sort_type}}", "hasLabel": "{{hasLabel}}"},
    },
    {
        "key": "client_porder_create",
        "case_name": "\u6570\u636e\u811a\u672c-\u63d0\u51fa\u914d\u9001\u5355",
        "url": "/client/porder.porderCreate",
        "body": {"create_type": "{{create_type}}", "porder_sn": "{{porder_sn}}", "logistics_id": "{{logistics_id}}", "porder_detail[0][order_detail_id]": "{{order_detail_id}}", "porder_detail[0][send_num]": "{{send_num}}"},
        "extract": {"porder_sn": "json.data.porder_sn"},
    },
    {
        "key": "admin_porder_detail",
        "case_name": "\u6570\u636e\u811a\u672c-\u914d\u9001\u5355\u8be6\u60c5",
        "url": "/porder.detail",
        "body": {"porder_sn": "{{porder_sn}}"},
    },
    {
        "key": "admin_porder_back_to_offer",
        "case_name": "数据脚本-配送单已报价退回待报价",
        "url": "/porder.backToOffer",
        "body": {"porder_sn": "{{porder_sn}}"},
    },
    {
        "key": "admin_porder_back_to_confirm",
        "case_name": "数据脚本-配送单待报价退回待装箱",
        "url": "/porder.backToConfirm",
        "body": {"porder_sn": "{{porder_sn}}"},
    },
    {
        "key": "admin_porder_to_wait_translate",
        "case_name": "数据脚本-配送单待装箱退回待翻译",
        "url": "/porder.toWaitTranslate",
        "body": {"porder_sn": "{{porder_sn}}"},
    },
    {
        "key": "admin_porder_submit_translate",
        "case_name": "\u6570\u636e\u811a\u672c-\u914d\u9001\u5355\u63d0\u4ea4\u914d\u8d27",
        "url": "/porder.submitTranslate",
        "body": {"porder_sn": "{{porder_sn}}", "client_remark_translate": "{{client_remark_translate}}", "list[0][id]": "{{porder_detail_id}}", "list[0][y_remark]": "{{y_remark}}", "is_temp": "{{is_temp}}"},
    },
    {
        "key": "admin_porder_add_box",
        "case_name": "\u6570\u636e\u811a\u672c-\u914d\u9001\u5355\u6dfb\u52a0\u7bb1\u5b50",
        "url": "/porder.addBox",
        "body": {"porder_sn": "{{porder_sn}}", "count": "{{box_count}}", "length": "{{box_length}}", "width": "{{box_width}}", "height": "{{box_height}}", "weight": "{{box_weight}}"},
    },
    {
        "key": "admin_porder_complete_box",
        "case_name": "\u6570\u636e\u811a\u672c-\u914d\u9001\u5355\u6807\u8bb0\u88c5\u7bb1\u5b8c\u6210",
        "url": "/porder.completeBox",
        "body": {"porder_sn": "{{porder_sn}}", "freight_id_set[0]": "{{freight_id}}", "count": "{{box_count}}", "length": "{{box_length}}", "width": "{{box_width}}", "height": "{{box_height}}", "weight": "{{box_weight}}"},
    },
    {
        "key": "admin_porder_into_box_preview",
        "case_name": "\u6570\u636e\u811a\u672c-\u914d\u9001\u5355\u88c5\u7bb1\u9884\u89c8",
        "url": "/porder.intoBoxPreview",
        "body": {"porderDetailIdS[0]": "{{porder_detail_id}}"},
    },
    {
        "key": "admin_porder_into_box_submit",
        "case_name": "\u6570\u636e\u811a\u672c-\u914d\u9001\u5355\u88c5\u7bb1\u63d0\u4ea4",
        "url": "/porder.intoBoxSubmit",
        "body": {"freight_id_set[0]": "{{freight_id}}", "list[0][per_num]": "{{box_num}}", "list[0][porder_detail_id]": "{{porder_detail_id}}", "list[0][stock][0][stock_id]": "{{stock_id}}", "list[0][stock][0][num_need]": "{{box_num}}"},
    },
    {
        "key": "admin_porder_to_wait_offer",
        "case_name": "\u6570\u636e\u811a\u672c-\u914d\u9001\u5355\u63d0\u4ea4\u4e1a\u52a1",
        "url": "/porder.toWaitOffer",
        "body": {"porder_sn": "{{porder_sn}}"},
    },
    {
        "key": "admin_porder_batch_update_freight_logistics",
        "case_name": "\u6570\u636e\u811a\u672c-\u914d\u9001\u5355\u9009\u62e9\u56fd\u9645\u7269\u6d41",
        "url": "/porder.batchUpdateFreightLogistics",
        "body": {"logistics_id": "{{delivery_quote_logistics_id}}", "freight_id_set[0]": "{{freight_id}}"},
    },
    {
        "key": "admin_porder_freight_list",
        "case_name": "\u6570\u636e\u811a\u672c-\u914d\u9001\u5355\u56fd\u9645\u8fd0\u8d39\u5217\u8868",
        "url": "/porder.freightList",
        "body": {"porder_sn": "{{porder_sn}}"},
    },
    {
        "key": "admin_spot_porder_detail",
        "case_name": "\u6570\u636e\u811a\u672c-\u914d\u9001\u5355\u88c5\u7bb1\u540e\u62bd\u68c0\u8be6\u60c5",
        "url": "/spot/spot/check/getSpotPorderDetail",
        "body": {"porder_sn": "{{porder_sn}}", "filterByFreightNum": "false"},
    },
    {
        "key": "admin_porder_amount_current",
        "case_name": "\u6570\u636e\u811a\u672c-\u914d\u9001\u5355\u91d1\u989d\u8ba1\u7b97",
        "url": "/porder.porderAmountCurrent",
        "body": {"porder_sn": "{{porder_sn}}"},
    },
    {
        "key": "admin_porder_submit_offer",
        "case_name": "\u6570\u636e\u811a\u672c-\u914d\u9001\u5355\u62a5\u4ef7",
        "url": "/porder.submitOffer",
        "body": {"porder_sn": "{{porder_sn}}", "list[0][id]": "{{porder_detail_id}}", "logistics_price_artificial": "{{logistics_price_artificial}}"},
    },
    {
        "key": "client_balance_pay",
        "case_name": "\u6570\u636e\u811a\u672c-\u4f59\u989d\u652f\u4ed8\u8ba2\u5355",
        "url": "/client/order.balancePayOrder",
        "body": {"order_sn": "{{order_sn}}", "discounts_id": "{{discounts_id}}", "predict_logistics_price_is_pay": "{{predict_logistics_price_is_pay}}"},
        "extract": {"order_sn": "json.data.order_sn"},
    },
    {
        "key": "client_bank_pay",
        "case_name": "\u6570\u636e\u811a\u672c-\u94f6\u884c\u652f\u4ed8\u8ba2\u5355",
        "url": "/client/order.bankPayOrder",
        "body": {"order_sn": "{{order_sn}}", "pay_bank_method": "{{pay_bank_method}}", "pay_date": "{{pay_date}}", "pay_reach_date": "{{pay_reach_date}}", "pay_name": "{{pay_name}}", "pay_amount": "{{pay_amount}}", "pay_remark": "{{pay_remark}}", "discounts_id": "{{discounts_id}}", "predict_logistics_price_is_pay": "{{predict_logistics_price_is_pay}}"},
        "extract": {"order_sn": "json.data.order_sn", "serial_number": "json.data.serial_number"},
    },
    {
        "key": "client_porder_balance_pay",
        "case_name": "\u6570\u636e\u811a\u672c-\u914d\u9001\u5355\u4f59\u989d\u4ed8\u6b3e",
        "url": "/client/porder.balancePayOrder",
        "body": {"porder_sn": "{{porder_sn}}", "discounts_id": "{{discounts_id}}", "merge_pay": "{{merge_pay}}"},
        "extract": {"porder_sn": "json.data.porder_sn"},
    },
    {
        "key": "client_porder_bank_pay",
        "case_name": "\u6570\u636e\u811a\u672c-\u914d\u9001\u5355\u94f6\u884c\u4ed8\u6b3e",
        "url": "/client/porder.bankPayOrder",
        "body": {"porder_sn": "{{porder_sn}}", "pay_bank_method": "{{pay_bank_method}}", "pay_date": "{{pay_date}}", "pay_reach_date": "{{pay_reach_date}}", "pay_name": "{{pay_name}}", "pay_amount": "{{pay_amount}}", "pay_remark": "{{pay_remark}}", "discounts_id": "{{discounts_id}}", "merge_pay": "{{merge_pay}}"},
        "extract": {"porder_sn": "json.data.porder_sn", "serial_number": "json.data.serial_number"},
    },
    {
        "key": "admin_login",
        "case_name": "\u6570\u636e\u811a\u672c-\u540e\u53f0\u767b\u5f55",
        "url": "/admin.login",
        "body": {"username": "{{backend_account}}", "password": "{{backend_password}}", "system": "{{backend_system}}", "compute_token": "{{backend_compute_token}}", "code": "{{backend_code}}"},
        "extract": {"adminToken": "json.data.access_token", "compute_token": "json.data.compute_token"},
    },
    {
        "key": "admin_balance_adjustment_client_info",
        "case_name": "数据脚本-出入金调整查询客户",
        "url": "/jpanfirm.clientInfo",
        "body": {"user_id": "{{customer_id}}"},
    },
    {
        "key": "admin_balance_adjustment_create",
        "case_name": "数据脚本-创建出入金调整申请",
        "url": "/bill.adjustApplication.create",
        "body": {
            "user_id": "{{customer_id}}",
            "adjust_reason": "{{adjust_reason}}",
            "type": "{{adjustment_type}}",
            "amount": "{{amount}}",
            "client_bill_reason": "{{client_bill_reason}}",
        },
    },
    {
        "key": "admin_balance_adjustment_list",
        "case_name": "数据脚本-出入金调整申请列表",
        "url": "/bill.adjustApplication.list",
        "body": {"keywords": "", "status": "{{status}}", "page": "1", "pageSize": "100"},
    },
    {
        "key": "admin_balance_adjustment_confirm",
        "case_name": "数据脚本-审核出入金调整申请",
        "url": "/bill.adjustApplication.confirm",
        "body": {"id": "{{application_id}}", "confirm_remark": "{{confirm_remark}}"},
    },
    {
        "key": "admin_order_detail",
        "case_name": "\u6570\u636e\u811a\u672c-\u540e\u53f0\u8ba2\u5355\u8be6\u60c5",
        "url": "/order.detail",
        "body": {"order_sn": "{{order_sn}}"},
    },
    {
        "key": "admin_order_back_to_wait_offer",
        "case_name": "数据脚本-订单已报价退回待报价",
        "url": "/order.backToWaitOffer",
        "body": {"order_sn_set[0]": "{{order_sn}}"},
    },
    {
        "key": "admin_order_back_to_wait_confirm",
        "case_name": "数据脚本-订单待报价退回订单采购",
        "url": "/order.backToWaitConfirm",
        "body": {"data": "{{data}}"},
    },
    {
        "key": "admin_order_back_to_wait_translate",
        "case_name": "数据脚本-订单采购退回订单翻译",
        "url": "/order.backToWaitTranslate",
        "body": {"order_sn_set[0]": "{{order_sn}}"},
    },
    {
        "key": "admin_order_translate",
        "case_name": "\u6570\u636e\u811a\u672c-\u8ba2\u5355\u7ffb\u8bd1\u63d0\u4ea4",
        "url": "/order.submitTranslate",
        "body": {"data": "{{data}}", "is_temp": "{{translate_is_temp}}"},
    },
    {
        "key": "admin_order_confirm",
        "case_name": "\u6570\u636e\u811a\u672c-\u91c7\u8d2d\u8c03\u67e5\u63d0\u4ea4",
        "url": "/order.submitConfirm",
        "body": {"order_sn": "{{order_sn}}", "data": "{{data}}", "is_temp": "{{confirm_is_temp}}"},
    },
    {
        "key": "admin_order_offer",
        "case_name": "\u6570\u636e\u811a\u672c-\u4e1a\u52a1\u62a5\u4ef7\u63d0\u4ea4",
        "url": "/order.submitOffer",
        "body": {"data": "{{data}}", "is_temp": "{{offer_is_temp}}"},
    },
    {
        "key": "admin_bill_merge_pay_detail",
        "case_name": "\u6570\u636e\u811a\u672c-\u8d22\u52a1\u786e\u8ba4\u5165\u91d1",
        "url": "/bill.mergePayDetail",
        "body": {"serial_number": "{{serial_number}}"},
    },
    {
        "key": "admin_bill_unconfirm_list",
        "case_name": "\u6570\u636e\u811a\u672c-\u8d22\u52a1\u5f85\u786e\u8ba4\u6c47\u6b3e\u5217\u8868",
        "url": "/bill.unConfirmList",
        "body": {"page": "{{page}}", "pageSize": "{{page_size}}", "serial_number": "{{serial_number}}", "order_sn": "{{order_sn}}"},
    },
    {
        "key": "admin_bill_confirm",
        "case_name": "\u6570\u636e\u811a\u672c-\u8d22\u52a1\u786e\u8ba4\u6c47\u6b3e",
        "url": "/bill.confirm",
        "body": {"id": "{{bill_id}}"},
    },
    {
        "key": "admin_purchase_list",
        "case_name": "\u6570\u636e\u811a\u672c-\u5f85\u62cd\u4e0b\u5546\u54c1\u5217\u8868",
        "url": "/purchase.purchaseList",
        "body": {"page": "{{page}}", "pageSize": "{{page_size}}", "status": "{{purchase_status}}", "order_sn": "{{order_sn}}"},
    },
    {
        "key": "admin_purchase_save_temp",
        "case_name": "\u6570\u636e\u811a\u672c-\u4fdd\u5b58\u91c7\u8d2d\u4ea4\u6613\u53f7",
        "url": "/purchase.saveTemp",
        "body": {"data": "{{data}}"},
    },
    {
        "key": "admin_purchase_to_wait_modify_price",
        "case_name": "\u6570\u636e\u811a\u672c-\u6807\u8bb0\u5f85\u6539\u4ef7",
        "url": "/purchase.toWaitModifyPrice",
        "body": {"ids": "{{ids}}", "purchase_no": "{{purchase_no}}"},
    },
    {
        "key": "admin_purchase_to_wait_pay",
        "case_name": "\u6570\u636e\u811a\u672c-\u63d0\u4ea4\u5f85\u8d22\u52a1\u4ed8\u6b3e",
        "url": "/purchase.toWaitPay",
        "body": {"data": "{{data}}", "ids": "{{ids}}"},
    },
    {
        "key": "admin_bill_purchase_wait_pay_list",
        "case_name": "\u6570\u636e\u811a\u672c-\u4ea4\u6613\u53f7\u5f85\u4ed8\u6b3e\u5217\u8868",
        "url": "/bill.purchaseWaitPayList",
        "body": {"page": "{{page}}", "pageSize": "{{page_size}}", "status": "{{finance_wait_pay_status}}", "purchase_no": "{{purchase_no}}"},
    },
    {
        "key": "admin_bill_purchase_wait_pay_confirm",
        "case_name": "\u6570\u636e\u811a\u672c-\u4ea4\u6613\u53f7\u4ed8\u6b3e\u786e\u8ba4",
        "url": "/bill.purchaseWaitPayConfirm",
        "body": {"purchaseNoSet": "{{purchaseNoSet}}"},
    },
    {
        "key": "admin_follow_list",
        "case_name": "\u6570\u636e\u811a\u672c-\u6838\u67e5\u5546\u54c1\u5217\u8868",
        "url": "/follow.followList",
        "body": {"page": "{{page}}", "pageSize": "{{page_size}}", "status": "{{follow_status}}", "purchase_no": "{{purchase_no}}", "order_sn": "{{order_sn}}"},
    },
    {
        "key": "admin_follow_up_preview",
        "case_name": "\u6570\u636e\u811a\u672c-\u6838\u67e5\u5546\u54c1\u9884\u89c8",
        "url": "/follow.upPreview",
        "body": {"purchase_no": "{{purchase_no}}", "express_no": "{{express_no}}"},
    },
    {
        "key": "admin_follow_start_checking",
        "case_name": "\u6570\u636e\u811a\u672c-\u5f00\u59cb\u6838\u67e5",
        "url": "/follow.startChecking",
        "body": {"purchaseIds": "{{purchaseIds}}"},
    },
    {
        "key": "admin_wms_grid_preview",
        "case_name": "\u6570\u636e\u811a\u672c-\u5e93\u4f4d\u9884\u89c8",
        "url": "/wms.wmsGridPreview",
        "body": {"shelf_type_set": "{{shelf_type_set}}", "user_id": "{{user_id}}", "order_purchase_id": "{{order_purchase_id}}"},
    },
    {
        "key": "admin_follow_up_storage",
        "case_name": "\u6570\u636e\u811a\u672c-\u4e0a\u67b6\u5165\u5e93",
        "url": "/follow.upStorage",
        "body": {"grid_id": "{{grid_id}}", "data": "{{data}}", "reconfirm": "{{reconfirm}}"},
    },
    {
        "key": "admin_box_list",
        "case_name": "\u6570\u636e\u811a\u672c-\u76f4\u63a5\u88c5\u7bb1\u7bb1\u5b50\u5217\u8868",
        "url": "/box.boxList",
        "body": {"status": "{{status}}", "order_sn": "{{order_sn}}"},
    },
    {
        "key": "admin_box_add_batch",
        "case_name": "\u6570\u636e\u811a\u672c-\u76f4\u63a5\u88c5\u7bb1\u6dfb\u52a0\u7bb1\u5b50",
        "url": "/box.addBoxBatch",
        "body": {"order_sn": "{{order_sn}}", "num": "{{num}}"},
    },
    {
        "key": "admin_box_update_attr",
        "case_name": "\u6570\u636e\u811a\u672c-\u76f4\u63a5\u88c5\u7bb1\u4fee\u6539\u7bb1\u89c4",
        "url": "/box.updateBoxAttr",
        "body": {"ids": "{{ids}}", "attr": "{{attr}}", "c": "{{c}}", "k": "{{k}}", "g": "{{g}}"},
    },
    {
        "key": "admin_box_update_weight",
        "case_name": "\u6570\u636e\u811a\u672c-\u76f4\u63a5\u88c5\u7bb1\u4fee\u6539\u91cd\u91cf",
        "url": "/box.updateBoxWeight",
        "body": {"ids": "{{ids}}", "weight": "{{weight}}"},
    },
    {
        "key": "admin_box_into_box",
        "case_name": "\u6570\u636e\u811a\u672c-\u76f4\u63a5\u88c5\u7bb1\u8d27\u7269\u88c5\u7bb1",
        "url": "/box.intoBox",
        "body": {"ids": "{{ids}}", "list": "{{list}}"},
    },
    {
        "key": "admin_box_delete",
        "case_name": "\u6570\u636e\u811a\u672c-\u76f4\u63a5\u88c5\u7bb1\u5220\u9664\u7bb1\u5b50",
        "url": "/box.deleteBox",
        "body": {"ids": "{{ids}}"},
    },
    {
        "key": "admin_box_to_complete",
        "case_name": "\u6570\u636e\u811a\u672c-\u76f4\u63a5\u88c5\u7bb1\u4e0a\u67b6\u5b8c\u6210",
        "url": "/box.toComplete",
        "body": {"ids": "{{ids}}", "grid_id": "{{grid_id}}", "grid_number": "{{grid_number}}"},
    },
]

OEM_DATA_SCRIPT_PROJECT_NAME = "oem-测试"

OEM_BASE_URL = "https://oemapi.rakumart.cn"

OEM_ADMIN_ORIGIN = "https://oemadmin.rakumart.cn"

OEM_FRONTEND_ORIGIN = "https://oem.rakumart.cn"

OEM_DATA_SCRIPT_API_CASES: List[Dict[str, Any]] = [
    {
        "key": "oem_admin_login",
        "case_name": "OEM-后台登录",
        "url": "/admin/login",
        "body": {"username": "{{backend_account}}", "password": "{{backend_password}}"},
        "extract": {"access_token": "json.data.access_token"},
    },
    {
        "key": "oem_client_login",
        "case_name": "OEM-前台登录",
        "url": "/api/login",
        "body": {"account": "{{account}}", "password": "{{password}}"},
        "extract": {"access_token": "json.data.access_token"},
    },
    {
        "key": "oem_new_inquiry",
        "case_name": "OEM-创建询价单",
        "url": "/api/newInquiry",
        "body": {
            "goods_name": "{{goods_name}}",
            "hope_min_price": "{{hope_min_price}}",
            "hope_max_price": "{{hope_max_price}}",
            "hope_futures": "{{hope_futures}}",
            "sku_info": [{"sku": "{{sku1}}", "num": "{{sku1_num}}"}, {"sku": "{{sku2}}", "num": "{{sku2_num}}"}],
            "is_temporarily": False,
            "goods_type": 1,
            "num": "{{num}}",
            "factory_urls": ["{{factory_url}}"],
            "factory_type": 3,
            "goods_img": "{{goods_img}}",
            "goods_other_img": ["{{goods_other_img}}"],
            "provide_prototype": False,
        },
        "extract": {"inquiry_sn": "json.data"},
    },
    {
        "key": "oem_exchange_rate",
        "case_name": "OEM-获取汇率",
        "url": "/common/common/getExchangeRate",
        "body": {},
    },
    {
        "key": "oem_user_info",
        "case_name": "OEM-用户信息",
        "url": "/api/userInfo",
        "body": {},
    },
    {
        "key": "oem_user_attention",
        "case_name": "OEM-用户关注信息",
        "url": "/api/user.attentionInfo",
        "body": {},
    },
    {
        "key": "oem_inquiry_num",
        "case_name": "OEM-询价单数量",
        "url": "/api/inquiryNum",
        "body": {"goods_type": "{{goods_type}}"},
    },
    {
        "key": "oem_inquiry_list",
        "case_name": "OEM-询价单列表",
        "url": "/api/inquiryList",
        "body": {
            "page": "{{page}}",
            "pageSize": "{{page_size}}",
            "status": "{{status}}",
            "order_sn": "{{order_sn}}",
            "start_time": "",
            "end_time": "",
            "goods_name": "",
            "goods_type": "",
        },
    },
    {
        # 询价单翻译流程：先调此接口拿阿里云 OSS STS 凭证，再 PUT 翻译文件到 OSS。
        # 供后续"提给采购"脚本使用，此处仅登记接口，不写脚本逻辑。
        "key": "oem_upload_token",
        "case_name": "OEM-询价单翻译文件上传",
        "url": "/common/common/getUploadToken",
        "body": {},
        "extract": {
            "AccessKeyId": "json.data.AccessKeyId",
            "AccessKeySecret": "json.data.AccessKeySecret",
            "SecurityToken": "json.data.SecurityToken",
            "Expiration": "json.data.Expiration",
        },
    },
    {
        # 后台接口：保存询价单翻译内容（需要后台 admin Bearer token）。
        # is_temp=false 保存；goods_file_tr 为翻译文件 OSS URL 列表。
        "key": "oem_inquiry_translate",
        "case_name": "OEM-询价单翻译保存",
        "url": "/admin/inquiryTranslate",
        "body": {
            "is_temp": False,
            "order_sn": "{{order_sn}}",
            "goods_name_tr": "{{goods_name_tr}}",
            "material_tr": "{{material_tr}}",
            "customize_detail_tr": "{{customize_detail_tr}}",
            "goods_detail_tr": "{{goods_detail_tr}}",
            "goods_file_tr": [{"file_url": "{{file_url}}", "file_name": "{{file_name}}"}],
            "sku_info": [
                {"id": "{{sku_id_1}}", "sku": "{{sku1}}", "sku_tr": "{{sku1_tr}}", "num": "{{sku1_num}}"},
                {"id": "{{sku_id_2}}", "sku": "{{sku2}}", "sku_tr": "{{sku2_tr}}", "num": "{{sku2_num}}"},
            ],
            "goods_id": "{{goods_id}}",
            "goods_class": "{{goods_class}}",
            "y_remark": "{{y_remark}}",
            "user_remark": "{{user_remark}}",
        },
        "extract": {"data": "json.data"},
    },
    {
        # 后台接口：翻译审核完成→提交给采购。翻译提交审核后调用此接口推进状态。
        "key": "oem_inquiry_translate_audit",
        "case_name": "OEM-翻译审核提交采购",
        "url": "/admin/inquiryTranslateAudit",
        "method": "POST",
        "headers": {"Authorization": "Bearer {{adminToken}}"},
        "body": {
            "order_sn": "{{order_sn}}",
        },
        "extract": {"data": "json.data"},
    },
    {
        # 后台接口：询价单流程节点提交（翻译完成/开始询价等，需后台 admin Bearer token）。
        # point_name 取值：translation=翻译提交采购，inquiry=进行询价提交。
        "key": "oem_inquiry_submit",
        "case_name": "OEM-询价单节点提交",
        "url": "/admin/inquiryDetail",
        "body": {
            "order_sn": "{{order_sn}}",
            "is_quote": False,
            "point_name": "{{point_name}}",
        },
        "extract": {"data": "json.data"},
    },
    {
        # 后台接口：开始询价（弹窗确认按钮，点击后才能进行询价，需后台 admin Bearer token）。
        # body 为询价单完整详情对象，实际使用时通常先 GET 详情再回传。
        "key": "oem_inquiry_start",
        "case_name": "OEM-开始询价",
        "url": "/admin/inquiryStartInquiry",
        "body": {
            "id": "{{inquiry_id}}",
            "user_id": "{{user_id}}",
            "order_sn": "{{order_sn}}",
            "user_status": 2,
            "admin_status": 0,
            "y_admin_status": 2,
            "g_admin_status": 1,
            "factory_type": "{{factory_type}}",
            "goods_id": "{{goods_id}}",
            "goods_no": "{{goods_no}}",
            "goods_type": "{{goods_type}}",
            "num": "{{num}}",
            "hope_futures": "{{hope_futures}}",
            "hope_min_price": "{{hope_min_price}}",
            "hope_max_price": "{{hope_max_price}}",
            "y_id": "{{y_id}}",
            "p_id": "{{p_id}}",
            "g_id": "{{g_id}}",
            "goods_class": "{{goods_class}}",
            "goods_img": "{{goods_img}}",
            "goods_name": "{{goods_name}}",
            "goods_name_tr": "{{goods_name_tr}}",
            "material": "{{material}}",
            "material_tr": "{{material_tr}}",
            "customize_detail": "{{customize_detail}}",
            "customize_detail_tr": "{{customize_detail_tr}}",
            "goods_detail": "{{goods_detail}}",
            "goods_detail_tr": "{{goods_detail_tr}}",
            "goods_file_tr": "{{goods_file_tr}}",
            "sku_info": "{{sku_info}}",
            "detail_list": "{{detail_list}}",
            "factory_url": "{{factory_url}}",
        },
        "extract": {"data": "json.data"},
    },
    {
        # 后台接口：编辑工厂信息（需后台 admin Bearer token）。
        # 用于更新询价单某条 detail 的工厂信息，factory_img 为 OSS 图片 URL。
        "key": "oem_factory_edit",
        "case_name": "OEM-编辑工厂",
        "url": "/admin/factoryEdit",
        "body": {
            "detail_id": "{{detail_id}}",
            "factory_iid": "{{factory_iid}}",
            "factory_name": "{{factory_name}}",
            "factory_province": "{{factory_province}}",
            "factory_city": "{{factory_city}}",
            "factory_img": "{{factory_img}}",
            "factory_url": "{{factory_url}}",
            "salesman": "{{salesman}}",
            "salesman_phone": "{{salesman_phone}}",
            "goods_url": "{{goods_url}}",
        },
        "extract": {"data": "json.data"},
    },
    {
        # 后台接口：工厂报价（需后台 admin Bearer token）。
        # 提交某条 detail 的工厂报价，含样品费用/大货费用/SKU 报价明细。
        "key": "oem_factory_quote",
        "case_name": "OEM-工厂报价",
        "url": "/admin/factoryQuote",
        "body": {
            "id": "{{detail_id}}",
            "order_sn": "{{order_sn}}",
            "status": 0,
            "g_cant_quote": 0,
            "is_read": 1,
            "factory_type": 1,
            "factory_submit_info": "{{factory_submit_info}}",
            "factory_iid": "{{factory_iid}}",
            "factory_name": "{{factory_name}}",
            "factory_province": "{{factory_province}}",
            "factory_city": "{{factory_city}}",
            "factory_url": "{{factory_url}}",
            "factory_img": "{{factory_img}}",
            "goods_url": "{{goods_url}}",
            "samples_other_fee": "{{samples_other_fee}}",
            "samples_freight": "{{samples_freight}}",
            "samples_delivery_time": "{{samples_delivery_time}}",
            "real_samples_other_fee": "{{real_samples_other_fee}}",
            "real_samples_freight": "{{real_samples_freight}}",
            "large_other_fee": "{{large_other_fee}}",
            "large_freight": "{{large_freight}}",
            "large_delivery_time": "{{large_delivery_time}}",
            "large_deposit_rate": "{{large_deposit_rate}}",
            "real_large_other_fee": "{{real_large_other_fee}}",
            "real_large_freight": "{{real_large_freight}}",
            "factory_salesman_id": 0,
            "warehouse_city": 0,
            "samples_warehouse_city": "{{samples_warehouse_city}}",
            "large_warehouse_city": "{{large_warehouse_city}}",
            "quote_admin": 0,
            "is_special_quote": False,
            "sku_detail": "{{sku_detail}}",
            "salesman": "{{salesman}}",
            "salesman_phone": "{{salesman_phone}}",
            "is_temporarily": False,
            "detail_id": "{{detail_id}}",
        },
        "extract": {"data": "json.data"},
    },
    {
        # 后台接口：询价完成（需后台 admin Bearer token）。
        # 工厂报价完成后点击"询价完成"，订单进入"询价完成未报价"状态。
        # body 为询价单完整详情对象，detail_list 含多家工厂报价明细
        # （实际可能多条 detail，每条 status=1 表示该工厂已报价）。
        "key": "oem_inquiry_complete",
        "case_name": "OEM-询价完成",
        "url": "/admin/inquiryComplete",
        "body": {
            "id": "{{inquiry_id}}",
            "user_id": "{{user_id}}",
            "order_sn": "{{order_sn}}",
            "user_status": 2,
            "admin_status": 0,
            "y_admin_status": 2,
            "g_admin_status": 2,
            "factory_type": "{{factory_type}}",
            "goods_id": "{{goods_id}}",
            "goods_no": "{{goods_no}}",
            "goods_type": "{{goods_type}}",
            "num": "{{num}}",
            "hope_futures": "{{hope_futures}}",
            "hope_min_price": "{{hope_min_price}}",
            "hope_max_price": "{{hope_max_price}}",
            "y_id": "{{y_id}}",
            "p_id": "{{p_id}}",
            "g_id": "{{g_id}}",
            "goods_class": "{{goods_class}}",
            "goods_img": "{{goods_img}}",
            "goods_name": "{{goods_name}}",
            "goods_name_tr": "{{goods_name_tr}}",
            "material": "{{material}}",
            "material_tr": "{{material_tr}}",
            "customize_detail": "{{customize_detail}}",
            "customize_detail_tr": "{{customize_detail_tr}}",
            "goods_detail": "{{goods_detail}}",
            "goods_detail_tr": "{{goods_detail_tr}}",
            "goods_file_tr": "{{goods_file_tr}}",
            "sku_info": "{{sku_info}}",
            "detail_list": "{{detail_list}}",
            "factory_url": "{{factory_url}}",
        },
        "extract": {"data": "json.data"},
    },
    {
        # 后台接口：报价给用户（需后台 admin Bearer token）。
        # 询价完成后，对每条 detail 执行报价给用户，status=1 表示已报价，
        # quote_admin/factory_salesman_id 已填充。实际可能多家工厂同时报价，
        # 脚本需对每个 detail 循环调用此接口。
        "key": "oem_factory_quote_to_user",
        "case_name": "OEM-报价给用户",
        "url": "/admin/factoryQuoteToUser",
        "body": {
            "id": "{{detail_id}}",
            "order_sn": "{{order_sn}}",
            "status": 1,
            "g_cant_quote": 0,
            "is_read": 0,
            "factory_type": 1,
            "factory_submit_info": "{{factory_submit_info}}",
            "factory_iid": "{{factory_iid}}",
            "factory_name": "{{factory_name}}",
            "factory_province": "{{factory_province}}",
            "factory_city": "{{factory_city}}",
            "factory_url": "{{factory_url}}",
            "factory_img": "{{factory_img}}",
            "goods_url": "{{goods_url}}",
            "samples_other_fee": "{{samples_other_fee}}",
            "samples_freight": "{{samples_freight}}",
            "samples_delivery_time": "{{samples_delivery_time}}",
            "real_samples_other_fee": "{{real_samples_other_fee}}",
            "real_samples_freight": "{{real_samples_freight}}",
            "large_other_fee": "{{large_other_fee}}",
            "large_freight": "{{large_freight}}",
            "large_delivery_time": "{{large_delivery_time}}",
            "large_deposit_rate": "{{large_deposit_rate}}",
            "real_large_other_fee": "{{real_large_other_fee}}",
            "real_large_freight": "{{real_large_freight}}",
            "factory_salesman_id": "{{factory_salesman_id}}",
            "warehouse_city": 0,
            "samples_warehouse_city": "{{samples_warehouse_city}}",
            "large_warehouse_city": "{{large_warehouse_city}}",
            "quote_admin": "{{quote_admin}}",
            "is_special_quote": False,
            "sku_detail": "{{sku_detail}}",
            "salesman": "{{salesman}}",
            "salesman_phone": "{{salesman_phone}}",
            "is_temporarily": False,
            "detail_id": "{{detail_id}}",
        },
        "extract": {"data": "json.data"},
    },
    {
        # 后台接口：询价单报价完成（需后台 admin Bearer token）。
        # 报价给用户完成后点击"报价完成"，订单进入"报价成功"状态。
        # body 为询价单完整详情，user_status/y_admin_status/g_admin_status 均为 3，
        # detail_list 每条 status=2（已报价给用户）。实际可能多家工厂同时报价。
        "key": "oem_inquiry_quote_complete",
        "case_name": "OEM-询价单报价完成",
        "url": "/admin/inquiryQuoteComplate",
        "body": {
            "id": "{{inquiry_id}}",
            "user_id": "{{user_id}}",
            "order_sn": "{{order_sn}}",
            "user_status": 3,
            "admin_status": 0,
            "y_admin_status": 3,
            "g_admin_status": 3,
            "factory_type": "{{factory_type}}",
            "goods_id": "{{goods_id}}",
            "goods_no": "{{goods_no}}",
            "goods_type": "{{goods_type}}",
            "num": "{{num}}",
            "hope_futures": "{{hope_futures}}",
            "hope_min_price": "{{hope_min_price}}",
            "hope_max_price": "{{hope_max_price}}",
            "y_id": "{{y_id}}",
            "p_id": "{{p_id}}",
            "g_id": "{{g_id}}",
            "goods_class": "{{goods_class}}",
            "goods_img": "{{goods_img}}",
            "goods_name": "{{goods_name}}",
            "goods_name_tr": "{{goods_name_tr}}",
            "material": "{{material}}",
            "material_tr": "{{material_tr}}",
            "customize_detail": "{{customize_detail}}",
            "customize_detail_tr": "{{customize_detail_tr}}",
            "goods_detail": "{{goods_detail}}",
            "goods_detail_tr": "{{goods_detail_tr}}",
            "goods_file_tr": "{{goods_file_tr}}",
            "sku_info": "{{sku_info}}",
            "detail_list": "{{detail_list}}",
            "factory_url": "{{factory_url}}",
        },
        "extract": {"data": "json.data"},
    },
    {
        # 后台接口：查询询价单完整详情（需后台 admin Bearer token）。
        # POST /admin/inquiryDetail 不带 point_name 即返回完整详情对象
        # （含 id/detail_list/sku_info/goods_class 等）。
        # 带 point_name 时为节点提交，是另一个语义。
        "key": "oem_inquiry_detail_query",
        "case_name": "OEM-询价单详情查询",
        "url": "/admin/inquiryDetail",
        "body": {"order_sn": "{{order_sn}}"},
        "extract": {"data": "json.data"},
    },
    {
        # 前台接口：大货单下单（需前台 Bearer token）。
        # 两步：/api/inquiryDetail → /api/quoteDetail
        "key": "oem_bulk_order",
        "case_name": "OEM-大货单下单",
        "url": "/api/inquiryDetail",
        "body": {"order_sn": "{{order_sn}}"},
    },
]
